apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: strimzi-kafka-operator
  namespace: kafka
spec:
  repo: https://strimzi.io/charts/
  chart: strimzi-kafka-operator
  version: 0.41.0
  targetNamespace: listen
  valuesContent: |-
    watchAnyNamespace: true
    featureGates: "+UseStrimziPodSets"
