apiVersion: v1
kind: Namespace
metadata:
  name: flink
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: flink-kubernetes-operator
  namespace: flink
spec:
  repo: https://apache.github.io/flink-kubernetes-operator
  chart: flink-kubernetes-operator
  version: 1.9.0
  targetNamespace: listen
  valuesContent: |-
    watchNamespaces:
    - listen
