apiVersion: v1
kind: Namespace
metadata:
  name: listen
  labels:
    layer: listen
---
apiVersion: v1
kind: Namespace
metadata:
  name: remember
  labels:
    layer: remember
---
apiVersion: v1
kind: Namespace
metadata:
  name: detect
  labels:
    layer: detect
---
apiVersion: v1
kind: Namespace
metadata:
  name: enforce
  labels:
    layer: enforce
---
apiVersion: v1
kind: Namespace
metadata:
  name: act
  labels:
    layer: act
